### ISSUE TITLE
use only JSX version

### ISSUE THREAD

**Issue by MohammedHady** [Lightstreamer/Lightstreamer-example-StockList-client-react#1]
can i edit and use jsx version without modifying or using js code

**Comment by Bravo27** [comment]
Since jsx is not supported in browsers by default we preferred transpile the jsx source code into plain js.
If you choose to edit the jsx files you will have to keep the plain js aligned using the aforementioned Babel (see "JSX" section of the README).

**Comment by MohammedHady** [comment]
i have ajax request to get data from Web API in componentDidMount function , but this request is fired alot of times creating multi trips to database i think this is happen because of light stramer

**Comment by Bravo27** [comment]
In the original demo the componentDidMount is called 10 times, exactly the number of Item in the table.

ITEMS: ["item1","item2","item3","item4","item5","item6","item7","item8","item9","item10"]

In each of this call we open a subscription versus the Lightstreamer server to receive real-time updates for a single stock.

If your database request  is not for single stock but global should be moved to a higher level of the code.
